# Generated by Django 5.0.6 on 2026-05-10 22:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Type de carburant',
                'verbose_name_plural': 'Types de carburant',
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=50)),
                ('capacity_liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_level_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('low_threshold_liters', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tanks', to='fuel.fueltype')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='stations.station')),
            ],
            options={
                'verbose_name': 'Cuve',
                'verbose_name_plural': 'Cuves',
                'ordering': ['station', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=50)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumps', to='stations.station')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pumps', to='fuel.tank')),
            ],
            options={
                'verbose_name': 'Pompe',
                'verbose_name_plural': 'Pompes',
                'ordering': ['station', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='TankReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('level_liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reading_type', models.CharField(choices=[('morning', 'Matin'), ('evening', 'Soir'), ('delivery', 'Livraison'), ('adjustment', 'Ajustement')], max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tank_readings', to=settings.AUTH_USER_MODEL)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='fuel.tank')),
            ],
            options={
                'verbose_name': 'Jaugeage',
                'verbose_name_plural': 'Jaugeages',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PumpReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('journal_date', models.DateField()),
                ('index_open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('index_close', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('return_volume', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='fuel.pump')),
            ],
            options={
                'verbose_name': 'Relevé index pompe',
                'verbose_name_plural': 'Relevés index pompes',
                'ordering': ['-journal_date', 'pump__display_order'],
                'unique_together': {('pump', 'journal_date')},
            },
        ),
    ]
