# Generated by Django 5.0.6 on 2026-06-05 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_rename_pump_to_nozzle'),
        ('stations', '0002_initial_journal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fueltype',
            options={'ordering': ['name'], 'verbose_name': 'Type de carburant', 'verbose_name_plural': 'Types de carburant'},
        ),
        migrations.AddField(
            model_name='fueltype',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_types', to='stations.station'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nozzle',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nozzles', to='stations.station'),
        ),
        migrations.AlterField(
            model_name='nozzle',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nozzles', to='fuel.tank'),
        ),
        migrations.AlterUniqueTogether(
            name='fueltype',
            unique_together={('station', 'code')},
        ),
    ]
