# Generated by Django 5.0.6 on 2026-05-10 22:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LubricantBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Marque lubrifiant',
                'verbose_name_plural': 'Marques lubrifiants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LubricantProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('packaging', models.CharField(blank=True, max_length=20)),
                ('sale_price_xof', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='lubricants.lubricantbrand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produit lubrifiant',
                'verbose_name_plural': 'Produits lubrifiants',
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LubricantStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='lubricants.lubricantproduct')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lubricant_stocks', to='stations.station')),
            ],
            options={
                'verbose_name': 'Stock lubrifiant',
                'verbose_name_plural': 'Stocks lubrifiants',
                'unique_together': {('product', 'station')},
            },
        ),
    ]
