# Generated by Django 5.0.6 on 2026-05-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lubricants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lubricantproduct',
            name='sale_price_xof',
        ),
        migrations.AddField(
            model_name='lubricantproduct',
            name='sale_price_boutique_xof',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lubricantproduct',
            name='sale_price_piste_xof',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
