# Generated by Django 5.0.6 on 2026-05-10 22:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie produit',
                'verbose_name_plural': 'Catégories produits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('purchase_price_xof', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale_price_xof', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.productcategory')),
            ],
            options={
                'verbose_name': 'Produit boutique',
                'verbose_name_plural': 'Produits boutique',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('low_threshold', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='shop.product')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='stations.station')),
            ],
            options={
                'verbose_name': 'Stock produit',
                'verbose_name_plural': 'Stocks produits',
                'unique_together': {('product', 'station')},
            },
        ),
    ]
