# Generated by Django 5.0.6 on 2026-05-10 22:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuel', '0001_initial'),
        ('gas', '0001_initial'),
        ('lubricants', '0002_remove_lubricantproduct_sale_price_xof_and_more'),
        ('shop', '0001_initial'),
        ('stations', '0002_initial_journal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('partial', 'Partiellement reçu'), ('received', 'Reçu'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('ordered_at', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='stations.station')),
            ],
            options={
                'verbose_name': 'Bon de commande',
                'verbose_name_plural': 'Bons de commande',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('delivered_at', models.DateField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('tank_level_before', models.DecimalField(blank=True, decimal_places=2, help_text='Niveau cuve avant livraison (litres)', max_digits=10, null=True)),
                ('tank_level_after', models.DecimalField(blank=True, decimal_places=2, help_text='Niveau cuve après livraison (litres)', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_deliveries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='stations.station')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='suppliers.purchaseorder')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('fuel', 'Carburant'), ('lubricant', 'Lubrifiant'), ('shop', 'Boutique'), ('gas', 'Gaz'), ('other', 'Autre')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(default='unité', max_length=20)),
                ('unit_price_xof', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuel.fueltype')),
                ('gas_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gas.gasbottleformat')),
                ('lubricant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lubricants.lubricantproduct')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.purchaseorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
            options={
                'verbose_name': 'Ligne BC',
                'verbose_name_plural': 'Lignes BC',
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('fuel', 'Carburant'), ('lubricant', 'Lubrifiant'), ('shop', 'Boutique'), ('gas', 'Gaz'), ('other', 'Autre')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('ordered_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Quantité commandée (0 si livraison sans BC)', max_digits=12)),
                ('received_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price_xof', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.delivery')),
                ('fuel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuel.fueltype')),
                ('gas_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gas.gasbottleformat')),
                ('lubricant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lubricants.lubricantproduct')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_items', to='suppliers.purchaseorderitem')),
            ],
            options={
                'verbose_name': 'Ligne livraison',
                'verbose_name_plural': 'Lignes livraison',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('fuel', 'Carburant'), ('lubricant', 'Lubrifiant'), ('shop', 'Boutique'), ('gas', 'Gaz'), ('other', 'Autre')], default='other', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='suppliers.supplier'),
        ),
    ]
