# Generated by Django 5.0.6 on 2026-05-10 22:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GasBottleFormat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('sale_price_xof', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_xof', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Format bouteille gaz',
                'verbose_name_plural': 'Formats bouteilles gaz',
                'ordering': ['weight_kg'],
            },
        ),
        migrations.CreateModel(
            name='GasBottleStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='gas.gasbottleformat')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_stocks', to='stations.station')),
            ],
            options={
                'verbose_name': 'Stock gaz',
                'verbose_name_plural': 'Stocks gaz',
                'unique_together': {('format', 'station')},
            },
        ),
    ]
