# Generated by Django 5.0.6 on 2026-05-16 20:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0002_alter_stationjournal_unique_together_and_more'),
        ('stations', '0002_initial_journal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('operational', 'Dépense opérationnelle'), ('petite_caisse', 'Petite caisse'), ('salary', 'Salaires'), ('other', 'Autre')], max_length=20)),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('amount_xof', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (FCFA)')),
                ('charge_date', models.DateField(verbose_name='Date de la dépense')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('check', 'Chèque')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence / Reçu')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='journal.stationjournal')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='stations.station')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_charges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
                'ordering': ['-charge_date', '-created_at'],
            },
        ),
    ]
