# Generated by Django 5.0.6 on 2026-05-10 22:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuel', '0001_initial'),
        ('lubricants', '0002_remove_lubricantproduct_sale_price_xof_and_more'),
        ('stations', '0002_initial_journal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StationJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('journal_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('journal_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'En cours'), ('closed', 'Clôturé'), ('validated', 'Validé')], default='draft', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_url', models.CharField(blank=True, max_length=500)),
                ('pdf_hash', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='stations.station')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal de station',
                'verbose_name_plural': 'Journaux de station',
                'ordering': ['-journal_date'],
                'unique_together': {('station', 'journal_date')},
            },
        ),
        migrations.CreateModel(
            name='JournalPaymentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_amount_xof', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tickets_amount_xof', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tpe_amount_xof', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('mobile_money_amount_xof', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit_amount_xof', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_summary', to='journal.stationjournal')),
            ],
            options={
                'verbose_name': 'Récap encaissements',
                'verbose_name_plural': 'Récaps encaissements',
            },
        ),
        migrations.CreateModel(
            name='JournalSalesRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('super', 'Super'), ('petrole', 'Pétrole'), ('gasoil', 'Gas-Oil'), ('lubs_boutique', 'Lubrifiants Boutique'), ('lubs_piste', 'Lubrifiants Piste'), ('graissage', 'Graissage'), ('vidange', 'Vidange'), ('lavage', 'Lavage'), ('autres', 'Autres / Divers'), ('boutique', 'Boutique'), ('gaz', 'Gaz')], max_length=20)),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit_price_xof', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_value_xof', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('previous_day_cumul_xof', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monthly_cumul_xof', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('previous_month_total_xof', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_recaps', to='journal.stationjournal')),
            ],
            options={
                'verbose_name': 'Récap ventes',
                'verbose_name_plural': 'Récaps ventes',
                'ordering': ['journal', 'category'],
                'unique_together': {('journal', 'category')},
            },
        ),
        migrations.CreateModel(
            name='JournalLubricantLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_open', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('purchased_qty', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('sold_qty', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('gauged_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('lubricant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='lubricants.lubricantproduct')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lubricant_lines', to='journal.stationjournal')),
            ],
            options={
                'verbose_name': 'Ligne lubrifiant',
                'verbose_name_plural': 'Lignes lubrifiants',
                'ordering': ['lubricant__brand__name', 'lubricant__name'],
                'unique_together': {('journal', 'lubricant')},
            },
        ),
        migrations.CreateModel(
            name='JournalFuelLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('index_close', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('return_volume', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('received_volume', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gauged_stock_open', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gauged_stock_close', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diff_comment', models.TextField(blank=True)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='fuel.pump')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_lines', to='journal.stationjournal')),
            ],
            options={
                'verbose_name': 'Ligne carburant',
                'verbose_name_plural': 'Lignes carburant',
                'ordering': ['pump__display_order'],
                'unique_together': {('journal', 'pump')},
            },
        ),
    ]
