# Generated by Django 5.0.6 on 2026-05-11 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial_journal'),
        ('stations', '0002_initial_journal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stationjournal',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='stationjournal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('station', 'journal_date'), name='unique_active_journal_per_station_date'),
        ),
    ]
