# Generated by Django 5.0.6 on 2026-06-05 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_rename_fuel_line_pump_to_nozzle'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalpaymentsummary',
            name='avoir_cash_xof',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='journalpaymentsummary',
            name='avoir_fuel_xof',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='JournalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('amount_xof', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('salaire', 'Salaires'), ('entretien', 'Entretien'), ('fourniture', 'Fournitures'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='journal.stationjournal')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['created_at'],
            },
        ),
    ]
