# Generated by Django 5.0.6 on 2026-06-05 14:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_add_expenses_and_avoir_fields'),
        ('stations', '0002_initial_journal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvoirWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('withdrawal_date', models.DateField()),
                ('withdrawal_type', models.CharField(choices=[('fuel', 'Carburant'), ('cash', 'Liquidités')], max_length=10)),
                ('amount_xof', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avoir_withdrawals', to='stations.station')),
            ],
            options={
                'verbose_name': 'Retrait avoir',
                'verbose_name_plural': 'Retraits avoir',
                'ordering': ['-withdrawal_date', '-created_at'],
            },
        ),
    ]
