# Generated by Django 5.0.6 on 2026-05-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='cash_tolerance_xof',
            field=models.DecimalField(decimal_places=2, default=500, help_text='Écart de caisse toléré en FCFA', max_digits=10),
        ),
        migrations.AddField(
            model_name='station',
            name='gauge_tolerance_pct',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Écart de jaugeage toléré en %', max_digits=5),
        ),
    ]
